add_newline = true

[aws]
disabled = true

[conda]
symbol = "ï„Œ "

[character]
success_symbol = "[ï”](bold fg:208)"
error_symbol = "[ï€](bold red)"

[dart]
symbol = "î˜ "
format = "[$symbol($version )]($style)"

[directory]
read_only = " ï€£"
truncate_to_repo = false
truncation_symbol = "â€¦/"
style = "blue"
repo_root_style = "underline blue"

[docker_context]
symbol = "ó°¡¨ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[gcloud]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = "ï˜ "
ignore_branches = ["main", "master"]

[git_status]
format = '([$all_status$ahead_behind]($style))'
ahead = "ï¢$count "
behind = "ï£$count "
diverged = "ï´$count "
untracked = "?$count "
stashed = "ï‰$count "
modified = "ï„Œ$count "
staged = "ï§$count "
renamed = "ï¡$count "
deleted = "îª$count "
conflicted = "ï„§$count "

[golang]
symbol = "î˜§ "
format = "[$symbol($version )]($style)"

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[line_break]
disabled = true

[memory_usage]
symbol = "ó°›"

[nim]
symbol = "ó°†¥"

[nix_shell]
symbol = "ï‹œ "

[nodejs]
format = "[$symbol($version )]($style)"
symbol = "î‰ "

[package]
symbol = "ï’‡ "
format = "[$symbol$version]($style) "
display_private = true

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[status]
symbol = ""
format = '[$symbol$common_meaning$signal_name$maybe_int ]($style)'
disabled = false
recognize_signal_code = true
map_symbol = true
not_executable_symbol = "ï "
not_found_symbol = "ó°‰ "
sigint_symbol = "ó°Ÿ¾ "

[swift]
symbol = "î• "

[cmd_duration]
format = "[ï€— $duration]($style) "

[hostname]
trim_at = ''
ssh_symbol = 'ğŸŒ'
format = '[$ssh_symbol$hostname]($style) '


[username]
format = '[$user]($style) '
